### ISSUE TITLE
Crashes all the time

### ISSUE THREAD

**Issue by GoogleFrog** [Spring-SpringBoard/SpringBoard-Core#111]
Trying to add terrain caused an error. Clicked around through the menus a bit more and the UI crashed.
[infolog.txt](https://github.com/Spring-SpringBoard/SpringBoard-Core/files/954382/infolog.txt)

**Comment by gajop** [comment]
There are probably many more errors (as I haven't really had time to sit and bugfix), but those contained in this infolog are fixed with the recent commits
