### ISSUE TITLE
SB is not generating script elements problem 

### ISSUE THREAD

**Issue by gajop** [Spring-SpringBoard/SpringBoard-Core#280]
It seems that it sometimes doesn't generate correct team/allyTeam (not sure how to replicate yet)

**Comment by Anarchid** [comment]
Here is my [project directory](https://www.dropbox.com/s/2aydu2glnw4tg6s/isar.7z?dl=0).

**Comment by sanguinariojoe** [comment]
The issue can be reproduced following this tutorial:

https://gitlab.com/Spring1944/spring1944/wikis/campaign/howto_setup

Let's see if I can fix that in the PR: https://github.com/Spring-SpringBoard/SpringBoard-Core/pull/297

**Comment by gajop** [comment]
fixed with https://github.com/Spring-SpringBoard/SpringBoard-Core/pull/297/commits/bbeb82fa51eb476b56e490236ee5329a79fd63dc
