### ISSUE TITLE
Some (windows?) users have issues with brush_textures sunfolder navigation

### ISSUE THREAD

**Issue by gajop** [Spring-SpringBoard/SpringBoard-Core#282]
For some reason it doesn't display subfolder names correctly for one user. It only happens for brush_textures, when viewed through an asset viewer, and only seems to affect some users.

**Comment by gajop** [comment]
I cannot reproduce this on Windows, Linux or Windows Wine emulation.

@ShoX1988, I would like to ask you to try the newest version of SB, and send me the infolog.
1. Grab newest SpringBoard
2. Open the console and type `/exec Spring.SetLogSectionFilterLevel("SpringBoard", "info")`
3. Navigate to Map->Texture->Paint, and click on Add.
4. Double click on the `core` folder.
5. Double click on the `blank` folder that you have reported to have.
6. Close SpringBoard and upload the infolog.

**Comment by ShoX1988** [comment]
The new version of springboard just seemed to work, textures loading up fine now. Do you still want me to do the above procedure and upload anyway?

**Comment by gajop** [comment]
@ShoX1988 
No, if everything works, that won't be necessary. 
I think it might've been fixed in either https://github.com/Spring-SpringBoard/SpringBoard-Core/commit/1470d13f2c89a10bab2f74cf7893bcb0d319bf90 or https://github.com/Spring-SpringBoard/SpringBoard-Core/commit/4944f2652b39c32e963753eec0453b978aed4cb7 and it wasn't delivered in our previous round of tests.

Thanks for testing!
