### ISSUE TITLE
Significant difference between reported consumed memory and Spring tracked one

### ISSUE THREAD

**Issue by sanguinariojoe** [Spring-SpringBoard/SpringBoard-Core#291]
I think the reported consumed memory using `garbagecollector` significantly differs from the LUA allocated memory computed by spring. I edited the spring engine as follows:

```
diff --git a/rts/lib/lua/include/LuaUser.cpp b/rts/lib/lua/include/LuaUser.cpp
index 0253e7455..394b552e7 100644
--- a/rts/lib/lua/include/LuaUser.cpp
+++ b/rts/lib/lua/include/LuaUser.cpp
@@ -177,7 +177,8 @@ const char* spring_lua_getHandleName(lua_State* L)
 ///////////////////////////////////////////////////////////////////////////
 // Custom Memory Allocator
 //
-static constexpr uint32_t maxAllocedBytes = 768u * (1024u * 1024u);
+// static constexpr uint32_t maxAllocedBytes = 768u * (1024u * 1024u);
+static constexpr uint32_t maxAllocedBytes = 2048u * (1024u * 1024u);
 static constexpr const char* maxAllocFmtStr = "[%s][handle=%s][OOM] synced=%d {alloced,maximum}={%u,%u}bytes\n";
 
 // tracks allocations across all states
@@ -215,6 +216,15 @@ void* spring_lua_alloc(void* ud, void* ptr, size_t osize, size_t nsize)
                return nullptr;
        }
 
+    if (nsize > osize) {
+        for (unsigned int i=0; i < 140; i++)
+        {
+            printf(" ");
+        }
+        printf("%lu MB", gLuaAllocState.allocedBytes.load() / (1024 * 1024));
+        printf("\r");
+    }
+
        if ((nsize > osize) && (gLuaAllocState.allocedBytes.load() > maxAllocedBytes)) {
                // (re)allocation
                // better kill Lua than whole engine; instant desync if synced handle
```

which is increasing the memory limit to 2GB, reporting at the same time the allocated LUA memory. The one used by spring to determine wether the memory limit is reached, raising the LUA alloc exception.

Well, while SpringBoard reports ~250MB, my stuff reports ~450MB.

I don't know whether we have a constant difference of ~200MB due to whatever allocation during the initialization, or such difference may change in time...

**Comment by sanguinariojoe** [comment]
Not your fault, just to bear in mind...
Also the memory reporting stuff is quite useful, so we can keep track of it...

**Comment by gajop** [comment]
Can you confirm that you are using the newest engine?
It should have `Spring.GetLuaMemUsage()` function, which provides better information, and includes memory usage from all Lua states. The `collectgarbage("count")` provides an incomplete picture as it only shows memory usage in LuaUI.

You can confirm whether you have the function by writing the following in the ingame console:
`/exec Spring.Echo(Spring.GetLuaMemUsage ~= nil)`

**Comment by sanguinariojoe** [comment]
In fact I'm not... I'm using 104.0. Thanks for the hint!
Is the newest engine already using OpenGL 4.X??

**Comment by gajop** [comment]
It's using OpenGL4, but additionally they're trying to drop the fixed function pipeline, and restrict it to the core context.
Still WIP afaik

**Comment by gajop** [comment]
Also, please let me know if you can reproduce the memory issue with the newest engine (or at least any that includes those Get*MemUsage functions)

**Comment by sanguinariojoe** [comment]
I'll do that next week! (I need the NVidia office computer :-p )

**Comment by sanguinariojoe** [comment]
Get*MemUsage functions seems to work pretty fine!

**Comment by sanguinariojoe** [comment]
BTW, 104 is consuming almost x2 memory than latest engine version...

**Comment by gajop** [comment]
Potentially related to https://zero-k.info/Forum/Thread/24623
I have a lot of memory so I didn't really notice any issue outright. Can you demonstrate it in a fashion that can be reproduced?

**Comment by sanguinariojoe** [comment]
Prolly...

1.- I can create a SB mutator that exit in the 2nd frame, when everything has been loaded, so you can get a perfect picture of the difference
2.- I can create a script to clone all the required packages (i.e. SB, custom SB memory report mutator, a map, and a game)
3.- I can create another script to download, patch to report memory in terminal, compile, and install both, spring-104 and spring-dev
4.- Finally, I can assemble all together in a script, which is also launching both instances and saving the logs

**Comment by sanguinariojoe** [comment]
I uploaded to the [repo](https://github.com/sanguinariojoe/SpringBoard-S44-memtest) all the stuff to make a memory benchmark with SpringBoard-S44 (Spring:1944). Unfortunately, Spring:1944 require some changes to properly works with latest engine version

WIP...

**Comment by gajop** [comment]
Woah, that's an amazing amount of dedication. I don't think I've ever seen people put that much effort into an issue :)

**Comment by sanguinariojoe** [comment]
jajaja

I LOVE MEMORY!

**Comment by sanguinariojoe** [comment]
This has been a bit overkilling, but very effective!

Latest engine version is consuming much less memory because it stop loading widgets/gadgets if a single error is detected in one of them... Holy crap! Jajaja
Indeed, it is consuming almost the same amount of memory after fixing all the errors...

**Comment by gajop** [comment]
I still like the dedication for putting up that mutator :) So keep it up if you can.

So... in conclusion, the original problem in this issue is fine with the newest engine and mods without errors?

**Comment by sanguinariojoe** [comment]
Yes! (I checked again)

**Comment by gajop** [comment]
Great. Turns out no change was needed, but I appreciate the effort. Thanks!
