### ISSUE TITLE
Assertion `matrix.IsOrthoNormal()' failed

### ISSUE THREAD

**Issue by sanguinariojoe** [Spring-SpringBoard/SpringBoard-Core#296]
See https://springrts.com/mantis/view.php?id=5863

When selecting units, for instance to create a trigger, is quite usual to get crashed with the following dump:

```
spring: /home/pepe/Downloads/spring/rts/Lua/LuaSyncedRead.cpp:586: int GetSolidObjectRotation(lua_State*, const CSolidObject*): Assertion `matrix.IsOrthoNormal()' failed.
Aborted (core dumped)
```

I sincerely thinks that is a spring engine bug... Let's see how evolves

**Comment by sanguinariojoe** [comment]
Kloot fixed that for 104+

https://springrts.com/mantis/view.php?id=5863

I'm afraid we should manually patch 104

**Comment by gajop** [comment]
hokomoko already included it in the maintenance branch for us :)
right now it's a bit slow to create an update to the wrapper to use the newer engine (more work is required to automate the process), so i'll delay with using the updated version for a while
