### ISSUE TITLE
Anarchid's map export issues: [f=0002080] Error: gl.RenderToTexture: error(-1) = (null)

### ISSUE THREAD

**Issue by gajop** [Spring-SpringBoard/SpringBoard-Core#329]
As reported: 
```
[f=0002080] [SpringBoard] Exporting map textures...
[f=0002080] [SpringBoard] Export complete.
[f=0002080] [SpringBoard] Saving the heightmap to springboard/projects/thornford_export_2/heightmap.png...
[f=0002080] [SpringBoard] Saving the grass to springboard/projects/thornford_export_2/grass.png...
[f=0002080] [SpringBoard] Saving the texture to springboard/projects/thornford_export_2/texture.png...
[f=0002080] Error: gl.RenderToTexture: error(-1) = (null)
[f=0002080] [SpringBoard] Error: <function>
```

@Anarchid:
> This is what i get when i try to export textures
> And grass doesn't contain textures i painted on to the map :frowning:
> Heightmap itself seems to work

Potentially two separate issues (grass textures not being saved and gl.RenderToTexture failing for diffuse), but tracking in one issue for now.

**Comment by Anarchid** [comment]
Grass is saved, but the image file contains basically downscaled unmodified diffuse. The texture mods are saved in scenario file mode, so at least i was able to use that with some sorcery.

**Comment by gajop** [comment]
Can you share some details on what the size of the map is? That might give
me a hint as to what the cause of the map export issue is.

Also, it would help if you tried to export it on a small map, like Red
Comet, and report back here.

**Comment by Anarchid** [comment]
The map is 14x14, i'll test on a smaller map tomorrow.

**Comment by gajop** [comment]
@Anarchid 
I've noticed that I have a similar issue if I use one of the static maintenance builds of Spring. (in particular I seem to have issues with the version we used during LD)

However, if I compile from maintenance branch myself, there are no issues!

So in conclusion, would you be able to compile Spring maintenance yourself, and check if this issue persists? If it does, I'd like to make a mantis bug report
