### ISSUE TITLE
Cloud Project Database Sharing

### ISSUE THREAD

**Issue by Beherrit** [Spring-SpringBoard/SpringBoard-Core#331]
As a user it would be nice to have the ability to share all current and previous work with the user base.  This feature could work much like Steam Workshop. Create, Upload, Share etc.

1. User can save file to an existing server where content is located
2. User will be able to pull projects/maps from this server to modify
3. Users can have separate folders for each game since some maps work differently based on the game

If all maps can be placed at a server location, can this be done engine side to allow all maps available to everyone so we do not need to download maps?  The only purpose to download maps would be for the purpose of single player/offline play.

**Comment by gajop** [comment]
This feature request is a bit unclear, and potentially out of scope for this project. 
While having a simple upload mechanism might help with the publication process, users can just as well manually use SpringFiles or other such site.

Having Springboard do a few things, but do them well feels more important than making it this complex file sharing system.

PS: I really didn't understand how we could not have to download maps. It's certainly always going to be necessary, as there are so many maps out there. Best we can do is provide good dl software or reasonable map packs for games (Springboard is not a game).

Therefore closing this issue. Feel free to open if you think I misunderstood you.
