### ISSUE TITLE
Sliders are difficult to control on Windows

### ISSUE THREAD

**Issue by gajop** [Spring-SpringBoard/SpringBoard-Core#362]
> Here, I got it. On my laptop the weird slider behavior happens even on windowed mode. Not sure if it's of any help, but I've noticed moving the slider to the right decreases the value (instead of reducing it as would be expected), when I push relatively fast in that direction - since the slider seems to be fighting back and moving it back to the other direction.

https://media.discordapp.net/attachments/288994979748249600/603667584218431651/2019-07-24_16-16-07.gif?width=400&height=204

**Comment by icexuick** [comment]
I have the same issue, though it's fighting a bit less in the last release... but still far from really usable.
