### ISSUE TITLE
Startup no LuaUI

### ISSUE THREAD

**Issue by seedship** [Spring-SpringBoard/SpringBoard-Core#380]
I downloaded the AppImage for linux and executed. After it gathered the required resources, it loaded TitanDuel, but there were no LuaUI menus, so I could not modify anything from the map.

Is this expected behavior? I didn't get any mod specific resources, but the manual didn't say I had to.

**Comment by gajop** [comment]
No, this is not expected behavior. Can you please send me your infolog? This can be done by clicking on the Systray (Spring) icon -> Toggle hide -> Upload Log. Then send me the link

**Comment by gajop** [comment]
My mistake, found the bug and it's fixed now
