### ISSUE TITLE
Exporting Spring Archive fails with error code: 127

### ISSUE THREAD

**Issue by The-Yak** [Spring-SpringBoard/SpringBoard-Core#417]
[f=0030638] [SpringBoard] Error: Export action failed: /tmp/.mount_SpringSi2jOT/bin/springMapConvNG: error while loading shared libraries: libIL.so.1: cannot open shared object file: No such file or directory

Compilation failed with error code: 127
[f=0030638] [SpringBoard] Error: Command failed: /tmp/.mount_SpringSi2jOT/bin/springMapConvNG: error while loading shared libraries: libIL.so.1: cannot open shared object file: No such file or directory

Compilation failed with error code: 127

[infolog.txt](https://github.com/Spring-SpringBoard/SpringBoard-Core/files/4859478/infolog.txt)

**Comment by gajop** [comment]
I was bundling a dynamically linked version of the compiler so this wasn't working on your system as you didn't have the devil libraries installed globally. I've now changed this to engine-distributed statically linked compiler version, which should fix the problem.

Thanks for the report!
